version: '3.8'

services:
# predict: # version du predict sans BentoML
#     build:
#       context: .
#       dockerfile: src/models/Dockerfile.predict
#     container_name: predict
#     ports:
#       - "8000:8000"
  ml-api:
      image: predict_service:latest # Si on refait un build plus tard, pensez à retagger la nouvelle image pareil
      container_name: accident-prediction-api
      ports:
        - "3000:3000"
      restart: unless-stopped
  streamlit:
    build:
      context: .
      dockerfile: src/streamlit/Dockerfile
    environment:
      - MODEL_API_URL=http://ml-api:3000
    ports:
      - "8501:8501"