version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.3
    ports:
      - "5000:5000"
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --artifacts-destination /app/mlruns --serve-artifacts --host 0.0.0.0 --port 5000
    volumes:
      - ./mlruns:/app/mlruns
  train:
    build:
      context: .
      dockerfile: src/train/Dockerfile
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./mlruns:/app/mlruns
  ml-api:
    image: ghcr.io/hugoperso/accident-prediction-api:latest
    container_name: accident-prediction-api
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      mlflow:
        condition: service_started
      train:
        condition: service_completed_successfully

  streamlit:
    build:
      context: .
      dockerfile: src/streamlit/Dockerfile
    environment:
      - MODEL_API_URL=http://ml-api:3000
    ports:
      - "8501:8501"
    depends_on:
      - ml-api