FROM python:3.9-slim

# Installation des dépendances
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copie du script
COPY predict_model.py .

# Commande par défaut
CMD ["uvicorn", "predict_model:app", "--host", "0.0.0.0", "--port", "8000"]