FROM python:3.9-slim

WORKDIR /app

COPY src/models/requirements.txt ./src/models/
RUN pip install --no-cache-dir -r src/models/requirements.txt

COPY src/ ./src/
COPY data/ ./data/

CMD ["python", "src/models/train_model.py"]